name: docker

on:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]
    paths:
      - .devcontainer/Dockerfile
      - .github/workflows/docker.yaml
  pull_request:
    branches: ["main"]
    paths:
      - .devcontainer/Dockerfile
      - .github/workflows/docker.yaml
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=pr
            type=sha,enable={{is_default_branch}},prefix={{date 'YYYYMMDD-HHmmss'}}-,suffix=,format=short

      # this action will take features and extensions into account
      - name: Build and Push devcontainer
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/${{ github.repository }}
          imageName: ghcr.io/${{ github.repository }}
          imageTag: ${{ join(steps.meta.outputs.tags) }}
          skipContainerUserIdUpdate: true
          platform: linux/amd64,linux/arm64
          runCmd: spin --version
